class AddVdnToDtCrs < ActiveRecord::Migration
  def change
    add_column :dt_crs, :vdn, :string
    add_column :dt_crs, :location, :string
    add_column :dt_crs, :address_1, :string
    add_column :dt_crs, :department, :string
    add_column :dt_crs, :address_2, :string
    add_column :dt_crs, :city, :string
    add_column :dt_crs, :state, :string
    add_column :dt_crs, :zip_code, :integer
    add_column :dt_crs, :country, :string
    add_column :dt_crs, :phone, :integer
    add_column :dt_crs, :fax, :integer
    add_column :dt_crs, :declined, :boolean
    add_column :dt_crs, :caller_type, :string
    add_column :dt_crs, :caller_first_name, :string
    add_column :dt_crs, :caller_last_name, :string
    add_column :dt_crs, :caller_title, :string
    add_column :dt_crs, :when_to_call, :text
    add_column :dt_crs, :caller_phone, :integer
    add_column :dt_crs, :caller_ext, :integer
    add_column :dt_crs, :caller_email, :string
    add_column :dt_crs, :how_did_you_learn, :string
    add_column :dt_crs, :unit, :string
    add_column :dt_crs, :name, :string
    add_column :dt_crs, :address_1_2, :string
    add_column :dt_crs, :address_2_2, :string
    add_column :dt_crs, :city_2, :string
    add_column :dt_crs, :state_2, :string
    add_column :dt_crs, :zip_code_2, :string
    add_column :dt_crs, :responsible_first_name_1, :string
    add_column :dt_crs, :responsible_last_name_1, :string
    add_column :dt_crs, :responsible_title_name_1, :string
    add_column :dt_crs, :responsible_description_1, :text
    add_column :dt_crs, :responsible_first_name_2, :string
    add_column :dt_crs, :responsible_last_name_2, :string
    add_column :dt_crs, :responsible_title_name_2, :string
    add_column :dt_crs, :responsible_description_2, :text
    add_column :dt_crs, :responsible_first_name_3, :string
    add_column :dt_crs, :responsible_last_name_3, :string
    add_column :dt_crs, :responsible_title_name_3, :string
    add_column :dt_crs, :responsible_description_3, :text
    add_column :dt_crs, :manager_first_name_1, :string
    add_column :dt_crs, :manager_last_name_1, :string
    add_column :dt_crs, :manager_title_name_1, :string
    add_column :dt_crs, :manager_phone_1, :integer
    add_column :dt_crs, :date_notified_1, :date
    add_column :dt_crs, :action_1, :text
    add_column :dt_crs, :manager_first_name_2, :string
    add_column :dt_crs, :manager_last_name_2, :string
    add_column :dt_crs, :manager_title_name_2, :string
    add_column :dt_crs, :manager_phone_2, :integer
    add_column :dt_crs, :date_notified_2, :date
    add_column :dt_crs, :action_2, :text
    add_column :dt_crs, :manager_first_name_3, :string
    add_column :dt_crs, :manager_last_name_3, :string
    add_column :dt_crs, :manager_title_name_3, :string
    add_column :dt_crs, :manager_phone_3, :integer
    add_column :dt_crs, :date_notified_3, :date
    add_column :dt_crs, :action_3, :text
    add_column :dt_crs, :involved_first_name_1, :string
    add_column :dt_crs, :involved_last_name_1, :string
    add_column :dt_crs, :involved_title_name_1, :string
    add_column :dt_crs, :involved_description_1, :text
    add_column :dt_crs, :involved_role_1, :string
    add_column :dt_crs, :involved_first_name_2, :string
    add_column :dt_crs, :involved_last_name_2, :string
    add_column :dt_crs, :involved_title_name_2, :string
    add_column :dt_crs, :involved_description_2, :text
    add_column :dt_crs, :involved_role_2, :string
    add_column :dt_crs, :involved_first_name_3, :string
    add_column :dt_crs, :involved_last_name_3, :string
    add_column :dt_crs, :involved_title_name_3, :string
    add_column :dt_crs, :involved_description_3, :text
    add_column :dt_crs, :involved_role_3, :string
    add_column :dt_crs, :when_incident_occurred, :string
    add_column :dt_crs, :incident_description, :text
    add_column :dt_crs, :where_incident_occurred, :string
    add_column :dt_crs, :how_do_you_know, :string
    add_column :dt_crs, :supporting_documentation, :text
    add_column :dt_crs, :code, :string
    add_column :dt_crs, :where, :string
    add_column :dt_crs, :when, :string
  end
end
